---
# Install Minio Server
- name: Install server
  include_tasks: install_server.yml
  when: minio_install_server

# Install Minio Client
- name: Install client
  include_tasks: install_client.yml
  when: minio_install_client

# Configure server/cluster
- name: Check if Minio Client exists
  ansible.builtin.stat:
    path: "{{ minio_client_bin }}"
  register: minio_client

- name: Configure server (requires Minio client installed)
  ansible.builtin.include_tasks: configure_server.yml
  when: minio_url|length > 0 and minio_client.stat.exists
  # run once per cluster
  run_once: true
